const BLOGS = [
  {
    id: 1,
    title: 'First Time Home Owner Ideas',
    description: '',
    src: 'images/post-1.jpg',
    author: 'Jones Mwakazi',
    date: '2023-12-12',
    featured: true,
  },
  {
    id: 2,
    title: 'How To Keep Your Furniture Clean',
    description: '',
    src: 'images/post-2.jpg',
    author: 'Caxton Ledama',
    date: '2023-09-17',
    featured: true,
  },
  {
    id: 3,
    title: 'Small Space Furniture Apartment Ideas',
    description: '',
    src: 'images/post-3.jpg',
    author: 'Bosco Mumo',
    date: '2024-01-10',
    featured: true,
  },
  {
    id: 4,
    title: 'First Time Home Owner Ideas',
    description: '',
    src: 'images/post-1.jpg',
    author: 'Jones Mwakazi',
    date: '2023-12-12',
    featured: false,
  },
  {
    id: 5,
    title: 'How To Keep Your Furniture Clean',
    description: '',
    src: 'images/post-2.jpg',
    author: 'Caxton Ledama',
    date: '2023-09-17',
    featured: false,
  },
  {
    id: 6,
    title: 'Small Space Furniture Apartment Ideas',
    description: '',
    src: 'images/post-3.jpg',
    author: 'Bosco Mumo',
    date: '2024-01-10',
    featured: false,
  },
  {
    id: 7,
    title: 'First Time Home Owner Ideas',
    description: '',
    src: 'images/post-1.jpg',
    author: 'Jones Mwakazi',
    date: '2023-12-12',
    featured: false,
  },
  {
    id: 8,
    title: 'How To Keep Your Furniture Clean',
    description: '',
    src: 'images/post-2.jpg',
    author: 'Caxton Ledama',
    date: '2023-09-17',
    featured: false,
  },
  {
    id: 9,
    title: 'Small Space Furniture Apartment Ideas',
    description: '',
    src: 'images/post-3.jpg',
    author: 'Bosco Mumo',
    date: '2024-01-10',
    featured: false,
  },
];

export default BLOGS;
